# Generated by Django 3.0.7 on 2020-07-12 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_album_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file_url',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj'])]),
        ),
    ]
