# Generated by Django 3.0.7 on 2020-06-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
