# Generated by Django 3.0.7 on 2020-07-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_auto_20200712_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
